CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; -- uuid support
CREATE EXTENSION IF NOT EXISTS pgcrypto; -- hash password

CREATE TYPE "itemType" AS ENUM (
  'livro',
  'materialDidatico'
);

CREATE TYPE "funcaoDoUsuario" AS ENUM (
  'administrador',
  'chefe',
  'estudante'
);

CREATE TYPE "emprestimoStatus" AS ENUM (
  'emAndamento',
  'concluido'
);

CREATE TABLE "Items" (
  "id" bigint,
  "type" "itemType",
  "descricao" text,
  "categoria" varchar(255),
  "dataDeAquisicao" date,
  "estadoDeConservacao" varchar(255),
  "localizacao" varchar(255),
  "uriImagem" text,
  PRIMARY KEY ("id", "type")
);

CREATE TABLE "Livros" (
  "ISBN" bigint,
  "type" "itemType" DEFAULT 'livro', -- CUIDADO
  "title" varchar(255) NOT NULL,
  "author" varchar(255) NOT NULL,
  PRIMARY KEY ("ISBN", "type")
);

CREATE TABLE "MateriaisDidaticos" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "type" "itemType" DEFAULT 'materialDidatico',
  "numeroDeSerie" int,
  PRIMARY KEY ("id", "type")
);

CREATE TABLE "Usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uriImagem" text,
  "funcao" "funcaoDoUsuario" NOT NULL DEFAULT 'estudante',
  "nome" varchar(255) NOT NULL,
  "sobrenome" varchar(255) NOT NULL,
  "login" varchar(255) UNIQUE NOT NULL,
  "hashSenha" char(60) NOT NULL,
  "authToken" uuid DEFAULT uuid_generate_v4() UNIQUE NOT NULL
);

CREATE TABLE "Emprestimos" (
  "dataDeEmprestimo" date DEFAULT (CURRENT_DATE),
  "dataDeDevolucaoPrevista" date NOT NULL DEFAULT (CURRENT_DATE + 7),
  "status" "emprestimoStatus" DEFAULT 'emAndamento',
  "userId" int,
  "itemId" bigint,
  "itemType" "itemType",
  PRIMARY KEY ("itemId", "itemType", "userId", "dataDeEmprestimo", "status")
);

ALTER TABLE "Livros" ADD FOREIGN KEY ("ISBN", "type") REFERENCES "Items" ("id", "type") ON DELETE CASCADE;

ALTER TABLE "MateriaisDidaticos" ADD FOREIGN KEY ("id", "type") REFERENCES "Items" ("id", "type") ON DELETE CASCADE;

ALTER TABLE "Emprestimos" ADD FOREIGN KEY ("userId") REFERENCES "Usuarios" ("id") ON DELETE CASCADE;

ALTER TABLE "Emprestimos" ADD FOREIGN KEY ("itemId", "itemType") REFERENCES "Items" ("id", "type") ON DELETE CASCADE;


